# Generated by Django 3.1.6 on 2021-02-14 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spicies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('last_time_feed', models.TimeField(max_length=255)),
                ('duration_feed', models.TimeField(max_length=255)),
                ('spicie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.spicies')),
            ],
        ),
    ]
